name: Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-arch:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          architecture: arm64
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          architecture: arm64
      - run: which ffmpeg
      - run: which ffprobe

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]

    steps:
      - uses: actions/checkout@v3
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - run: ffmpeg -version
      - run: ffprobe -version
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: git
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: git
      - run: ffmpeg -version
      - run: ffprobe -version
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: '5.1.1'
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: '5.1.1'
      - run: ffmpeg -version
      - run: ffprobe -version

  test-shared:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: '6.1.1'
          linking-type: shared
      - name: Run FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: 'release'
          linking-type: shared
      - run: ffmpeg -version
      - run: ffprobe -version
      - run: dir ${{ steps.setup-ffmpeg.outputs.ffmpeg-path }}
